import React from "react";
import { Link } from "react-router-dom";

const Privacy = () => {
  return (
    <div className="max-w-[442px] mx-auto px-[12px]">
      <div>
        <Link to="/ProfilePage" className=" sticky top-0">
          <p className="  text-white py-3 px-4 rounded-sm items-center  bg-blue-500">
            <span className=" text-[20px]">&#x3c;</span> Privacy Policy
          </p>
        </Link>
        <div className="px-3 ">
          <p className="text-[17px] capitalize mt-2">
            the privacy policy describes .our polices and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <h1 className=" text-[35px] mt-3 leading-10 font-semibold">
            Interpretation and Definitions
          </h1>
          <p className="text-[20px] mt-4 mb-2 font-medium">Interpretation</p>
          <p className="">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions.
          </p>
          <p className="mt-2">
            The following definitions shall have the same meaning regardless of
            whether they appear in singular or in plural.
          </p>
          <p className="text-[20px] mt-4  font-medium">Definitions</p>
          <p className="">For the purposes of this Privacy Policy:</p>
          <li>
            <span className=" font-medium">You</span> means the individual
            accessing or using the Service, or the company, or other legal
            entity on behalf of which such individual is accessing or using the
            Service, as applicable.
          </li>
          <li>
            <span className=" font-medium"> Company</span> (referred to as
            either "the Company", "We", "Us" or "Our" in this Agreement) refers
            to colour predication
          </li>
          <li>
            <span className=" font-medium">Affiliate</span> means an entity that
            controls, is controlled by or is under common control with a party,
            where "control" means ownership of 50% or more of the shares, equity
            interest or other securities entitled to vote for election of
            directors or other managing authority.
          </li>
          <li>
            <span className=" font-medium">Account</span> means a unique account
            created for You to access our Service or parts of our Service.
          </li>
          <li>
            <span className=" font-medium">Service</span> refers to the Website.
          </li>
          <li>
            <span className="font-medium">Country</span> refers to: Uttar
            Pradesh, India
          </li>
          <li>
            <span className="font-medium">Service</span> Provider means any
            natural or legal person who processes the data on behalf of the
            Company. It refers to third-party companies or individuals employed
            by the Company to facilitate the Service, to provide the Service on
            behalf of the Company, to perform services related to the Service or
            to assist the Company in analyzing how the Service is used.
          </li>
          <li>
            <span className="font-medium">Third-party</span> Social Media
            Service refers to any website or any social network website through
            which a User can log in or create an account to use the Service.
            Personal Data is any information that relates to an identified or
            identifiable individual.
          </li>
          <li>
            <span className=" font-medium">Cookies</span> are small files that
            are placed on Your computer, mobile device or any other device by a
            website, containing the details of Your browsing history on that
            website among its many uses.
          </li>
          <li>
            <span className=" font-medium">Device</span> means any device that
            can access the Service such as a computer, a cellphone or a digital
            tablet.
          </li>
          <li>
            <span className=" font-medium">Usage</span> Data refers to data
            collected automatically, either generated by the use of the Service
            or from the Service infrastructure itself (for example, the duration
            of a page visit).
          </li>
          <h2 className=" text-[30px] mt-3 leading-10 font-semibold">
            Collecting and Using Your Personal Data
          </h2>
          <p className=" text-[20px] font-medium mt-3">Personal Data</p>
          <p className=" mt-3">
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>
          <li>Email address </li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
          <p className=" mt-3 text-[20px] font-medium">Usage Data</p>
          <p className=" mt-2">
            Usage Data is collected automatically when using the Service.
          </p>
          <p className=" mt-2">
            Usage Data may include information such as Your Device's Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </p>
          <p className=" mt-2">
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data.
          </p>
          <p className=" mt-2">
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </p>
          <p className=" font-medium text-[20px] mt-3 ">
            Tracking Technologies and Cookies
          </p>
          <p className=" mt-2">
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze Our Service.
          </p>
          <p className=" mt-2">
            You can instruct Your browser to refuse all Cookies or to indicate
            when a Cookie is being sent. However, if You do not accept Cookies,
            You may not be able to use some parts of our Service.
          </p>
          <p className=" mt-2">
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
            remain on your personal computer or mobile device when You go
            offline, while Session Cookies are deleted as soon as You close your
            web browser.
          </p>
          <p className="font-medium text-[20px] mt-3 ">
            Retention of Your Personal Data
          </p>
          <p className=" mt-2 px-2">
            The Company will retain Your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will
            retain and use Your Personal Data to the extent necessary to comply
            with our legal obligations (for example, if we are required to
            retain your data to comply with applicable laws), resolve disputes,
            and enforce our legal agreements and policies.
          </p>
          <p className=" mt-2 px-2">
            The Company will also retain Usage Data for internal analysis
            purposes. Usage Data is generally retained for a shorter period of
            time, except when this data is used to strengthen the security or to
            improve the functionality of Our Service, or We are legally
            obligated to retain this data for longer time periods.
          </p>
          <p className="font-medium text-[20px] mt-3 ">
            Transfer of Your Personal Data
          </p>
          <p>
            Your information, including Personal Data, is processed at the
            Company's operating offices and in any other places where the
            parties involved in the processing are located. It means that this
            information may be transferred to — and maintained on — computers
            located outside of Your state, province, country or other
            governmental jurisdiction where the data protection laws may differ
            than those from Your jurisdiction.
          </p>
          <p className=" mt-2">
            Your consent to this Privacy Policy followed by Your submission of
            such information represents Your agreement to that transfer.
          </p>
          <p className=" mt-2">
            The Company will take all steps reasonably necessary to ensure that
            Your data is treated securely and in accordance with this Privacy
            Policy and no transfer of Your Personal Data will take place to an
            organization or a country unless there are adequate controls in
            place including the security of Your data and other personal
            information.
          </p>
          <p className="font-medium text-[20px] mt-3 ">
            Disclosure of Your Personal Data
          </p>
          <p className=" mt-2 font-medium">Business Transactions</p>
          <p>
            If the Company is involved in a merger, acquisition or asset sale,
            Your Personal Data may be transferred. We will provide notice before
            Your Personal Data is transferred and becomes subject to a different
            Privacy Policy.
          </p>
          <p className=" mt-2 font-medium">Law enforcement</p>
          <p>
            Under certain circumstances, the Company may be required to disclose
            Your Personal Data if required to do so by law or in response to
            valid requests by public authorities (e.g. a court or a government
            agency).
          </p>
          <p className=" mt-2 font-medium">Other legal requirements</p>
          <p className=" mt-3">
            The Company may disclose Your Personal Data in the good faith belief
            that such action is necessary to:
          </p>
          <li className=" mt-3">Comply with a legal obligation</li>
          <li> Protect and defend the rights or property of the Company</li>
          <li>
            Prevent or investigate possible wrongdoing in connection with the
            Service
          </li>
          <li>
            Protect the personal safety of Users of the Service or the public
          </li>
          <li>Protect against legal liability</li>
          <p className=" font-medium text-[23px] mt-3">
            Security of Your Personal Data
          </p>
          <p className=" mt-2">
            The security of Your Personal Data is important to Us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While We strive to use
            commercially acceptable means to protect Your Personal Data, We
            cannot guarantee its absolute security.
          </p>
          <p className=" font-medium text-[35px] mt-3">Children's Privacy</p>
          <p>
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If You are a parent or guardian and You are
            aware that Your child has provided Us with Personal Data, please
            contact Us. If We become aware that We have collected Personal Data
            from anyone under the age of 13 without verification of parental
            consent, We take steps to remove that information from Our servers.
          </p>
          <p className=" mt-2">
            If We need to rely on consent as a legal basis for processing Your
            information and Your country requires consent from a parent, We may
            require Your parent's consent before We collect and use that
            information.
          </p>
          <p className=" font-medium text-[25px] mt-3">
            Links to Other Websites
          </p>
          <p>
            Our Service may contain links to other websites that are not
            operated by Us. If You click on a third party link, You will be
            directed to that third party's site. We strongly advise You to
            review the Privacy Policy of every site You visit.
          </p>
          <p className=" mt-2">
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </p>
          <p className=" font-medium text-[25px] mt-3">
            Changes to this Privacy Policy
          </p>
          <p>
            We may update our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.
          </p>
          <p className=" mt-2">
            {" "}
            We will let You know via email and/or a prominent notice on Our
            Service, prior to the change becoming effective and update the "Last
            updated" date at the top of this Privacy Policy.
          </p>
          <p className=" mt-2">
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>
          <p className="font-medium text-[25px] mt-3">Contact Us</p>
          <p className=" px-2">
            If you have any questions about this Privacy Policy,
            You can contact us:
          </p>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
